lang: fr
title: "Sécheresses : ne pas être pris par surprise"
description: "À quel point nous allons manquer d'eau en France ?"
logo: /assets/img/logo.png
image: /assets/img/capture-printemps-2050.png
twitter:
  card: summary_large_image

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ":categories/:slug/"
  - scope:
      path: "assets/img"
    values:
      image: true
